// import _ from 'lodash';
import axios from 'axios';

// const OPENAPI_DOMAIN_WITH_PREFIX_AND_PROTOCOL =_.startsWith(location.href, 'https') ? DEFINE_FULL_OPENAPI_DOMAIN_WITH_HTTPS_PREFIX : DEFINE_FULL_OPENAPI_DOMAIN_WITH_HTTP_PREFIX;
const OPENAPI_DOMAIN_WITH_PREFIX_AND_PROTOCOL = DEFINE_HAS_HTTPS_SERVER ? DEFINE_FULL_OPENAPI_DOMAIN_WITH_HTTPS_PREFIX : DEFINE_FULL_OPENAPI_DOMAIN_WITH_HTTP_PREFIX;

// const API_DOMAIN_WITH_PREFIX_AND_PROTOCOL = _.startsWith(location.href, 'https') ? DEFINE_FULL_API_DOMAIN_WITH_HTTPS_PREFIX : DEFINE_FULL_API_DOMAIN_WITH_HTTP_PREFIX;
const API_DOMAIN_WITH_PREFIX_AND_PROTOCOL = DEFINE_HAS_HTTPS_SERVER ? DEFINE_FULL_API_DOMAIN_WITH_HTTPS_PREFIX : DEFINE_FULL_API_DOMAIN_WITH_HTTP_PREFIX;

// const UNION_DOMAIN_WITH_PREFIX_AND_PROTOCOL = _.startsWith(location.href, 'https') ? DEFINE_FULL_UNION_DOMAIN_WITH_HTTPS_PREFIX : DEFINE_FULL_UNION_DOMAIN_WITH_HTTP_PREFIX;
const UNION_DOMAIN_WITH_PREFIX_AND_PROTOCOL = DEFINE_HAS_HTTPS_SERVER ? DEFINE_FULL_UNION_DOMAIN_WITH_HTTPS_PREFIX : DEFINE_FULL_UNION_DOMAIN_WITH_HTTP_PREFIX;

const http = axios.create({
  // eslint-disable-next-line no-dupe-keys
  baseURL: API_DOMAIN_WITH_PREFIX_AND_PROTOCOL,
  withCredentials: true,
});

export {
  UNION_DOMAIN_WITH_PREFIX_AND_PROTOCOL,

  API_DOMAIN_WITH_PREFIX_AND_PROTOCOL,

  OPENAPI_DOMAIN_WITH_PREFIX_AND_PROTOCOL,
};

export default http;
